[package]
name = "bevy_mesh_terrain"
description = "A simple and ergonomic heightmap terrain plugin for Bevy game engine"
version = "0.6.5"
edition = "2021"
authors = [ "ethereumdegen" ]
license = "MIT"
readme = "readme.md"
repository = "https://github.com/ethereumdegen/bevy_mesh_terrain"
exclude = [ "/assets/", "/examples/" ]
keywords = [ "terrain" , "bevy" ]


[dependencies]
anyhow = "1.0.75"
bevy = "0.12.0"
bevy_mod_sysfail = "6.0.0"
futures-lite = "1.13.0"
image = "0.24.7" 
png = "0.17.11"
ron = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
 

thiserror = "1.0.48"
 
 
 #maybe put a modifier on this like 'physics'
 bevy_xpbd_3d = { version = "0.3", features = ["simd","serialize"] }
serde_json = "1.0.113"
bincode = "1.3.3"
 
[[example]]
name = "basic"
path = "examples/basic.rs"


 